// android/settings.gradle.kts

import java.util.Properties
import java.io.FileInputStream

// 1) Read flutter.sdk from local.properties (generated by Flutter)
//    Fallback to environment variable FLUTTER_SDK if needed.
val localProperties = Properties()
val localPropertiesFile = file("local.properties")
if (localPropertiesFile.exists()) {
    FileInputStream(localPropertiesFile).use { stream ->
        localProperties.load(stream)
    }
}

val flutterSdkPath = localProperties.getProperty("flutter.sdk")
    ?: System.getenv("FLUTTER_SDK")
    ?: throw GradleException(
        "Flutter SDK not found. " +
                "Please define flutter.sdk in android/local.properties " +
                "or set FLUTTER_SDK environment variable."
    )

// 2) Make Flutter's Gradle plugins available to this build
includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

// 3) Usual Android settings
rootProject.name = "my_asset_app2"

// If your module name is not ':app', change it here.
include(":app")
